DROP SEQUENCE CIT;
DROP SEQUENCE PRO;
DROP TRIGGER CIT_INC;
DROP TRIGGER PRO_INC;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE FRIENDS;

DROP TABLE USER_CURRENT_CITY;
DROP TABLE USER_HOMETOWN_CITY;


DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;


DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;


DROP TABLE TAGS;
DROP TABLE MESSAGE;

DROP TABLE ALBUMS CASCADE CONSTRAINTS;

DROP TABLE PHOTOS CASCADE CONSTRAINTS;

DROP TABLE CITIES;
