INSERT INTO USERS
SELECT DISTINCT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER
FROM weile.PUBLIC_USER_INFORMATION U
WHERE U.USER_ID NOT IN(SELECT USER_ID FROM USERS);

INSERT INTO FRIENDS
SELECT DISTINCT USER1_ID, USER2_ID
FROM weile.PUBLIC_ARE_FRIENDS U;


INSERT INTO CITIES(CITY_NAME,STATE_NAME,COUNTRY_NAME)
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY
FROM weile.PUBLIC_USER_INFORMATION
WHERE HOMETOWN_CITY IS NOT NULL OR HOMETOWN_STATE IS NOT NULL OR HOMETOWN_COUNTRY IS NOT NULL
UNION
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY
FROM weile.PUBLIC_USER_INFORMATION
WHERE CURRENT_CITY IS NOT NULL OR CURRENT_STATE IS NOT NULL OR CURRENT_COUNTRY IS NOT NULL
UNION
SELECT DISTINCT EVENT_CITY, EVENT_STATE, EVENT_COUNTRY
FROM weile.PUBLIC_EVENT_INFORMATION
WHERE EVENT_CITY IS NOT NULL OR EVENT_STATE IS NOT NULL OR EVENT_COUNTRY IS NOT NULL;

INSERT INTO USER_CURRENT_CITY
SELECT DISTINCT U.USER_ID, C.CITY_ID 
FROM weile.PUBLIC_USER_INFORMATION U
INNER JOIN CITIES C
ON U.CURRENT_CITY=C.CITY_NAME AND U.CURRENT_STATE=C.STATE_NAME AND U.CURRENT_COUNTRY=C.COUNTRY_NAME;
--WHERE (U.USER_ID, C.CITY_ID) NOT IN (SELECT (USER_ID , CURRENT_CITY_ID) FROM USER_CURRENT_CITY);


INSERT INTO USER_HOMETOWN_CITY
SELECT DISTINCT U.USER_ID, C.CITY_ID 
FROM weile.PUBLIC_USER_INFORMATION U
INNER JOIN CITIES C
ON U.HOMETOWN_CITY=C.CITY_NAME AND U.HOMETOWN_STATE=C.STATE_NAME AND U.HOMETOWN_COUNTRY=C.COUNTRY_NAME;

INSERT INTO PROGRAMS(INSTITUTION, CONCENTRATION, DEGREE)
SELECT DISTINCT INSTITUTION_NAME, PROGRAM_CONCENTRATION, PROGRAM_DEGREE
FROM weile.PUBLIC_USER_INFORMATION
WHERE INSTITUTION_NAME IS NOT NULL OR PROGRAM_CONCENTRATION IS NOT NULL OR PROGRAM_DEGREE IS NOT NULL;

INSERT INTO EDUCATION
SELECT DISTINCT U.USER_ID, P.PROGRAM_ID, I.PROGRAM_YEAR
FROM weile.PUBLIC_USER_INFORMATION I,PROGRAMS P,USERS U
WHERE U.USER_ID=I.USER_ID AND P.INSTITUTION=I.INSTITUTION_NAME AND P.CONCENTRATION=I.PROGRAM_CONCENTRATION AND P.DEGREE=I.PROGRAM_DEGREE;

INSERT INTO USER_EVENTS
SELECT DISTINCT E.EVENT_ID,E.EVENT_CREATOR_ID,E.EVENT_NAME,E.EVENT_TAGLINE,E.EVENT_DESCRIPTION,E.EVENT_HOST,
	E.EVENT_TYPE,E.EVENT_SUBTYPE,E.EVENT_LOCATION, C.CITY_ID,E.EVENT_START_TIME, E.EVENT_END_TIME
FROM weile.PUBLIC_EVENT_INFORMATION E
INNER JOIN CITIES C
ON E.EVENT_CITY=C.CITY_NAME AND E.EVENT_STATE=C.STATE_NAME AND E.EVENT_COUNTRY=C.COUNTRY_NAME;

INSERT INTO ALBUMS
SELECT DISTINCT ALBUM_ID, OWNER_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, COVER_PHOTO_ID
FROM weile.PUBLIC_PHOTO_INFORMATION;

INSERT INTO PHOTOS
SELECT DISTINCT PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK
FROM weile.PUBLIC_PHOTO_INFORMATION;

INSERT INTO TAGS
SELECT DISTINCT * FROM weile.PUBLIC_TAG_INFORMATION;
